### ISSUE TITLE
blocking calls

### ISSUE THREAD

**Issue by txdv** [sendanor/node-getent#1]
Hello,
just wanted to let you know that you are basically wrapping blocking calls which will block the entire event loop in node if there are a lot of parallel calls on those functions by other threads/processes.

**Comment by thejhh** [comment]
Are you sure? As far as I recall V8 C++ extension side does not block the JavaScript side event thread. Although my experience comes from Google V8 engine programming and it might be really outdated.

Do you have suggestion how to fix it? Can you make a test that proofs this (which can be used to verify fix for this issue)?

**Comment by txdv** [comment]
I'm saying that getpwent is a blocking call.

If you look at the [glibc implementation](https://github.com/lattera/glibc/blob/master/pwd/fgetpwent_r.c#L77-L105) you see that flock and unflock is used.

According to the [man doc of flock](http://linux.die.net/man/2/flock) they are blocking functions:

> A call to flock() may block if an incompatible lock is held by another process.

If you want to fix this you need to call it at least in a thread pool.

**Comment by thejhh** [comment]
Yes, it is blocking code in C++/OS, but AFAIK it does not block the JavaScript engine thread -- which is running background in v8 engine -- at least it didn't when I implemented working JavaScript-based thread support into v8 few years ago. 

These C++ extensions didn't have any kind of thread safety back then unless you did it yourself and there was only one thread for running JavaScript code (which also means only one JavaScript thread calls C++ extensions by default).

However you are right -- these functions should not be called in parallel, but that is different problem.

I'm not sure if I'm right in this matter, I might be wrong, and I have no time to investigate this at this time. Although I think blocking way of calling these functions would probably be better for this library because of the nature of these functions.

**Comment by txdv** [comment]
Can you point me to the code of that JavaScript background thread support?

I'll investigate it.

**Comment by thejhh** [comment]
It's really old project, from time before Node.js was invented, at https://github.com/jheusala/openjs/tree/master/src/openjs/extensions/thread

However it's not working in Node.js because there is no thread safety implemented in Node.js.

Hmm, I looked that code and saw that I had used `v8::Unlocker unlocker;` there: http://bespin.cz/~ondras/html/classv8_1_1Unlocker.html

**Comment by thejhh** [comment]
I think we probably could do same as I did in our [node-crypt3](https://github.com/sendanor/node-crypt3/issues/14)

**Comment by thejhh** [comment]
I simply don't have time at the moment to do it. Maybe in few months... but unless someone pays for my time or does a pull request, it isn't going to be sooner.

**Comment by jsumners** [comment]
Yes, you'd have to do it the way you did in `node-crypt3`. There are only a few instances where Node uses the thread pool, and C++ add-ons are not automatically one of those. Also, there are only 4 threads available by default, so it's still not a great solution to the problem ([ref]).

[ref]: https://youtu.be/P9csgxBgaZ8?list=PLfMzBWSH11xYaaHMalNKqcEurBH8LstB8&t=1029
